# Generated by Django 3.2.10 on 2022-01-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('sito', models.CharField(max_length=80, null=True)),
                ('lat', models.CharField(max_length=80, null=True)),
                ('long', models.CharField(max_length=80, null=True)),
                ('indirizzo', models.CharField(max_length=80, null=True)),
                ('comune', models.CharField(max_length=80, null=True)),
                ('provincia', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('telefono', models.CharField(max_length=80, null=True)),
                ('descrizione', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'palestra',
                'verbose_name_plural': 'palestre',
                'db_table': 'Gyms',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('data_inizio', models.DateField(auto_now_add=True)),
                ('data_fine', models.DateField(auto_now=True)),
                ('descrizione', models.CharField(max_length=200)),
                ('docente', models.CharField(max_length=20)),
                ('idGym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corsi', to='app.gyms')),
            ],
            options={
                'verbose_name': 'corso',
                'verbose_name_plural': 'corsi',
                'db_table': 'Courses',
            },
        ),
    ]
