# Generated by Django 3.2.10 on 2022-01-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('immagine', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
                'db_table': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='courses',
            name='idGym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corso', to='app.gyms'),
        ),
        migrations.AddField(
            model_name='courses',
            name='idCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='app.category'),
        ),
    ]
