# Generated by Django 3.2.10 on 2022-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220124_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='durata',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='data_fine',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='data_inizio',
            field=models.DateField(null=True),
        ),
    ]
